/*  This file is part of Winyl Player source code.
    Copyright (C) 2008-2018, Alex Kras. <winylplayer@gmail.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#pragma once

static const WCHAR* radio_181[] = {
// Pop
L"Pop",
L"Power 181 (Top 40)",
L"http://www.181.fm/winamp.pls?station=181-power&file=181-power.pls",
L"Pop",
L"Old School HipHop/RnB",
L"http://www.181.fm/winamp.pls?station=181-oldschool&file=181-oldschool.pls",
L"Pop",
L"UK top 40",
L"http://www.181.fm/winamp.pls?station=181-uktop40&file=181-uktop40.pls",
L"Pop",
L"The Vibe of Vegas",
L"http://www.181.fm/winamp.pls?station=181-vibe&file=181-vibe.pls",
L"Pop",
L"The Heart (Love Songs)",
L"http://www.181.fm/winamp.pls?station=181-heart&file=181-heart.pls",
L"Pop",
L"Smooth AC",
L"http://www.181.fm/winamp.pls?station=181-smoothac&file=181-smoothac.pls",
L"Pop",
L"The Office",
L"http://www.181.fm/winamp.pls?station=181-office&file=181-office.pls",
L"Pop",
L"The Mix",
L"http://www.181.fm/winamp.pls?station=181-themix&file=181-themix.pls",
L"Pop",
L"The Point",
L"http://www.181.fm/winamp.pls?station=181-thepoint&file=181-thepoint.pls",
L"Pop",
L"Party 181",
L"http://www.181.fm/winamp.pls?station=181-party&file=181-party.pls",
// Rock
L"Rock",
L"The Buzz (Alt. Rock)",
L"http://www.181.fm/winamp.pls?station=181-buzz&file=181-buzz.pls",
L"Rock",
L"Classic Buzz (Alt)",
L"http://www.181.fm/winamp.pls?station=181-classicbuzz&file=181-classicbuzz.pls",
L"Rock",
L"The Rock! (Hard Rock)",
L"http://www.181.fm/winamp.pls?station=181-hardrock&file=181-hardrock.pls",
L"Rock",
L"Rock 181",
L"http://www.181.fm/winamp.pls?station=181-rock&file=181-rock.pls",
L"Rock",
L"Chloe @181.FM",
L"http://www.181.fm/winamp.pls?station=181-chloe&file=181-chloe.pls",
L"Rock",
L"The Eagle (Classic)",
L"http://www.181.fm/winamp.pls?station=181-eagle&file=181-eagle.pls",
L"Rock",
L"Rock 40 (Rock & Roll)",
L"http://www.181.fm/winamp.pls?station=181-rock40&file=181-rock40.pls",
L"Rock",
L"The Point",
L"http://www.181.fm/winamp.pls?station=181-thepoint&file=181-thepoint.pls",
L"Rock",
L"80's Hairband",
L"http://www.181.fm/winamp.pls?station=181-hairband&file=181-hairband.pls",
//L"Rock",
//L"Punk | Hardcore",
//L"http://www.181.fm/winamp.pls?station=181-punk&file=181-punk.pls",
// Urban
L"Urban",
L"The Beat (HipHop/R&B)",
L"http://www.181.fm/winamp.pls?station=181-beat&file=181-beat.pls",
L"Urban",
L"Old School HipHop/RnB",
L"http://www.181.fm/winamp.pls?station=181-oldschool&file=181-oldschool.pls",
L"Urban",
L"True R&B",
L"http://www.181.fm/winamp.pls?station=181-rnb&file=181-rnb.pls",
L"Urban",
L"The Box (Urban)",
L"http://www.181.fm/winamp.pls?station=181-thebox&file=181-thebox.pls",
//L"Urban",
//L"Trinity HipHop",
//L"http://www.181.fm/winamp.pls?station=181-trinity&file=181-trinity.pls",
L"Urban",
L"Jammin 181",
L"http://www.181.fm/winamp.pls?station=181-jammin&file=181-jammin.pls",
L"Urban",
L"Soul",
L"http://www.181.fm/winamp.pls?station=181-soul&file=181-soul.pls",
// Dance
L"Dance",
L"Energy 98",
L"http://www.181.fm/winamp.pls?station=181-energy98&file=181-energy98.pls",
L"Dance",
L"Techno Club",
L"http://www.181.fm/winamp.pls?station=181-technoclub&file=181-technoclub.pls",
L"Dance",
L"Energy 93 (Euro EDM)",
L"http://www.181.fm/winamp.pls?station=181-energy93&file=181-energy93.pls",
L"Dance",
L"Studio 181",
L"http://www.181.fm/winamp.pls?station=181-ball&file=181-ball.pls",
L"Dance",
L"90's Dance",
L"http://www.181.fm/winamp.pls?station=181-90sdance&file=181-90sdance.pls",
L"Dance",
L"Chilled Out",
L"http://www.181.fm/winamp.pls?station=181-chilled&file=181-chilled.pls",
L"Dance",
L"The Vibe of Vegas",
L"http://www.181.fm/winamp.pls?station=181-vibe&file=181-vibe.pls",
// Country
L"Country",
L"Kickin' Country",
L"http://www.181.fm/winamp.pls?station=181-kickincountry&file=181-kickincountry.pls",
L"Country",
L"Real Country",
L"http://www.181.fm/winamp.pls?station=181-realcountry&file=181-realcountry.pls",
L"Country",
L"90's Country",
L"http://www.181.fm/winamp.pls?station=181-90scountry&file=181-90scountry.pls",
L"Country",
L"US 181",
L"http://www.181.fm/winamp.pls?station=181-us181&file=181-us181.pls",
L"Country",
L"80's Country",
L"http://www.181.fm/winamp.pls?station=181-80scountry&file=181-80scountry.pls",
L"Country",
L"Highway 181",
L"http://www.181.fm/winamp.pls?station=181-highway&file=181-highway.pls",
L"Country",
L"Front Porch (Bluegrass)",
L"http://www.181.fm/winamp.pls?station=181-frontporch&file=181-frontporch.pls",
// Easy Listening
L"Easy Listening",
L"The Breeze",
L"http://www.181.fm/winamp.pls?station=181-breeze&file=181-breeze.pls",
L"Easy Listening",
L"Classical Guitar",
L"http://www.181.fm/winamp.pls?station=181-classicalguitar&file=181-classicalguitar.pls",
L"Easy Listening",
L"Classical Jazz",
L"http://www.181.fm/winamp.pls?station=181-classicaljazz&file=181-classicaljazz.pls",
L"Easy Listening",
L"Vocal Jazz",
L"http://www.181.fm/winamp.pls?station=181-vocals&file=181-vocals.pls",
L"Easy Listening",
L"BeBop Jazz",
L"http://www.181.fm/winamp.pls?station=181-bebop&file=181-bebop.pls",
L"Easy Listening",
L"Sensual World",
L"http://www.181.fm/winamp.pls?station=181-sensual&file=181-sensual.pls",
L"Easy Listening",
L"Fusion Jazz",
L"http://www.181.fm/winamp.pls?station=181-fusionjazz&file=181-fusionjazz.pls",
L"Easy Listening",
L"Trance Jazz",
L"http://www.181.fm/winamp.pls?station=181-trancejazz&file=181-trancejazz.pls",
L"Easy Listening",
L"True Blues",
L"http://www.181.fm/winamp.pls?station=181-blues&file=181-blues.pls",
L"Easy Listening",
L"Classical Music",
L"http://www.181.fm/winamp.pls?station=181-classical&file=181-classical.pls",
L"Easy Listening",
L"Acid Jazz",
L"http://www.181.fm/winamp.pls?station=181-acidjazz&file=181-acidjazz.pls",
// Latin
L"Latin",
L"Reggae Roots",
L"http://www.181.fm/winamp.pls?station=181-reggae&file=181-reggae.pls",
L"Latin",
L"Salsa",
L"http://www.181.fm/winamp.pls?station=181-salsa&file=181-salsa.pls",
// Talk Radio
L"Talk Radio",
L"Comedy Club",
L"http://www.181.fm/winamp.pls?station=181-comedy&file=181-comedy.pls",
// Oldies
L"Oldies",
L"Beatles",
L"http://www.181.fm/winamp.pls?station=181-beatles&file=181-beatles.pls",
L"Oldies",
L"Soul",
L"http://www.181.fm/winamp.pls?station=181-soul&file=181-soul.pls",
L"Oldies",
L"Mellow Gold",
L"http://www.181.fm/winamp.pls?station=181-mellow&file=181-mellow.pls",
L"Oldies",
L"Classic Hits 181",
L"http://www.181.fm/winamp.pls?station=181-greatoldies&file=181-greatoldies.pls",
L"Oldies",
L"Good Time Oldies",
L"http://www.181.fm/winamp.pls?station=181-goodtime&file=181-goodtime.pls",
L"Oldies",
L"Super 70s",
L"http://www.181.fm/winamp.pls?station=181-70s&file=181-70s.pls",
// 80's Decade
L"80's Decade",
L"80's Country",
L"http://www.181.fm/winamp.pls?station=181-80scountry&file=181-80scountry.pls",
L"80's Decade",
L"Awesome 80's",
L"http://www.181.fm/winamp.pls?station=181-awesome80s&file=181-awesome80s.pls",
L"80's Decade",
L"Lite 80's",
L"http://www.181.fm/winamp.pls?station=181-lite80s&file=181-lite80s.pls",
// 90's Decade
L"90's Decade",
L"Star 90's",
L"http://www.181.fm/winamp.pls?station=181-star90s&file=181-star90s.pls",
L"90's Decade",
L"90's Country",
L"http://www.181.fm/winamp.pls?station=181-90scountry&file=181-90scountry.pls",
L"90's Decade",
L"Lite 90's",
L"http://www.181.fm/winamp.pls?station=181-lite90s&file=181-lite90s.pls",
L"90's Decade",
L"90's Alternative",
L"http://www.181.fm/winamp.pls?station=181-90salt&file=181-90salt.pls",
L"90's Decade",
L"90's Dance",
L"http://www.181.fm/winamp.pls?station=181-90sdance&file=181-90sdance.pls",
// Christmas
L"Christmas",
L"Kountry",
L"http://www.181.fm/winamp.pls?station=181-xkkountry&file=181-xkkountry.pls",
L"Christmas",
L"Classics",
L"http://www.181.fm/winamp.pls?station=181-xtraditional&file=181-xtraditional.pls",
L"Christmas",
L"Oldies",
L"http://www.181.fm/winamp.pls?station=181-xoldies&file=181-xoldies.pls",
L"Christmas",
L"Country",
L"http://www.181.fm/winamp.pls?station=181-xcountry&file=181-xcountry.pls",
L"Christmas",
L"Power",
L"http://www.181.fm/winamp.pls?station=181-xpower&file=181-xpower.pls",
L"Christmas",
L"Highway",
L"http://www.181.fm/winamp.pls?station=181-xhighway&file=181-xhighway.pls",
L"Christmas",
L"Soundtracks",
L"http://www.181.fm/winamp.pls?station=181-xsoundtrax&file=181-xsoundtrax.pls",
L"Christmas",
L"R&B",
L"http://www.181.fm/winamp.pls?station=181-xtrue&file=181-xtrue.pls",
L"Christmas",
L"Rock",
L"http://www.181.fm/winamp.pls?station=181-xrock&file=181-xrock.pls",
L"Christmas",
L"Mix",
L"http://www.181.fm/winamp.pls?station=181-xmix&file=181-xmix.pls",
L"Christmas",
L"Fun",
L"http://www.181.fm/winamp.pls?station=181-xfun&file=181-xfun.pls",
L"Christmas",
L"Kids",
L"http://www.181.fm/winamp.pls?station=181-xkids&file=181-xkids.pls",
L"Christmas",
L"Blender",
L"http://www.181.fm/winamp.pls?station=181-xblender&file=181-xblender.pls",
L"Christmas",
L"Standards",
L"http://www.181.fm/winamp.pls?station=181-xstandards&file=181-xstandards.pls",
L"Christmas",
L"Spirit",
L"http://www.181.fm/winamp.pls?station=181-xspirit&file=181-xspirit.pls",
L"Christmas",
L"Smooth Jazz",
L"http://www.181.fm/winamp.pls?station=181-xsmooth&file=181-xsmooth.pls",
L"Christmas",
L"Gospel",
L"http://www.181.fm/winamp.pls?station=181-xgospel&file=181-xgospel.pls",
L"Christmas",
L"Swing",
L"http://www.181.fm/winamp.pls?station=181-xswing&file=181-xswing.pls",
};

static const WCHAR* radio_977[] = {
L"80s",
L"http://977music.com/itunes/80s.pls",
L"90s",
L"http://www.977music.com/itunes/90s.pls",
L"Alternative",
L"http://www.977music.com/itunes/alternative.pls",
L"Classic Rock",
L"http://www.977music.com/itunes/classicrock.pls",
L"Comedy",
L"http://www.977music.com/itunes/comedy.pls",
L"Country",
L"http://www.977music.com/977hicountry.pls",
L"Hitz",
L"http://977music.com/itunes/hitz.pls",
L"Jams",
L"http://www.977music.com/itunes/jamz.pls",
L"Mix",
L"http://www.977music.com/itunes/mix.pls",
L"Oldies",
L"http://www.977music.com/itunes/oldies.pls",
L"Smooth Jazz",
L"http://www.977music.com/itunes/jazz.pls",
};

static const WCHAR* radio_Soma[] = {
L"BAGeL Radio", // OLD 480 Minutes
L"https://somafm.com/bagel130.pls",
L"Beat Blender",
L"https://somafm.com/beatblender130.pls",
L"Black Rock FM",
L"https://somafm.com/brfm130.pls",
L"Boot Liquor",
L"https://somafm.com/bootliquor320.pls",
//L"Christmas Lounge",
//L"http://somafm.com/christmas.pls",
//L"Christmas Rocks!",
//L"http://somafm.com/xmasrocks130.pls",
L"cliqhop idm",
L"https://somafm.com/cliqhop256.pls",
L"Covers",
L"https://somafm.com/covers130.pls",
L"Deep Space One",
L"https://somafm.com/deepspaceone130.pls",
L"DEF CON Radio",
L"https://somafm.com/defcon256.pls",
L"Digitalis",
L"https://somafm.com/digitalis130.pls",
//L"Doomed",
//L"http://somafm.com/doomed130.pls",
L"Drone Zone",
L"https://somafm.com/dronezone256.pls",
L"Dub Step Beyond",
L"https://somafm.com/dubstep256.pls",
//L"Earwaves",
//L"http://somafm.com/earwaves130.pls",
L"Fluid",
L"https://somafm.com/fluid130.pls",
L"Folk Forward",
L"https://somafm.com/folkfwd130.pls",
L"Groove Salad",
L"https://somafm.com/groovesalad256.pls",
//L"Iceland Airwaves",
//L"http://somafm.com/wma128/airwaves.asx",
L"Illinois Street Lounge",
L"https://somafm.com/illstreet130.pls",
L"Indie Pop Rocks!",
L"https://somafm.com/indiepop130.pls",
L"Left Coast 70s",
L"https://somafm.com/seventies320.pls",
L"Lush",
L"https://somafm.com/lush130.pls",
L"Metal Detector",
L"https://somafm.com/metal130.pls",
L"Mission Control",
L"https://somafm.com/missioncontrol130.pls",
L"PopTron",
L"https://somafm.com/poptron130.pls",
L"Secret Agent",
L"https://somafm.com/secretagent130.pls",
L"Seven Inch Soul",
L"https://somafm.com/7soul130.pls",
L"SF 10-33",
L"https://somafm.com/sf1033130.pls",
L"Sonic Universe",
L"https://somafm.com/sonicuniverse192.pls",
//L"South by Soma",
//L"http://somafm.com/wma128/sxfm.asx",
L"Space Station Soma",
L"https://somafm.com/spacestation130.pls",
L"Suburbs of Goa",
L"https://somafm.com/suburbsofgoa130.pls",
//L"The Silent Channel",
//L"http://somafm.com/silent130.pls",
L"The Trip",
L"https://somafm.com/thetrip130.pls",
L"ThistleRadio",
L"https://somafm.com/thistle130.pls",
L"Underground 80s",
L"https://somafm.com/u80s256.pls",
//L"Xmas in Frisko",
//L"http://somafm.com/xmasinfrisko.pls",
};

static const WCHAR* radio_DI[] = {
L"9Axis Trance",
L"https://orion.shoutca.st/tunein/asx9axis.pls",
L"ALYF Recordings",
L"https://orion.shoutca.st/tunein/asxaiyf.pls",
L"ATG Trance",
L"https://orion.shoutca.st/tunein/asxcobley.pls",
L"Ahmed Romel Trance",
L"https://orion.shoutca.st/tunein/asxromel.pls",
L"Ambient & Lounge",
L"https://orion.shoutca.st/tunein/asxambient.pls",
L"Ambient Fantasy",
L"https://orion.shoutca.st/tunein/asxfantasy.pls",
L"Ambient Nature Sounds",
L"https://orion.shoutca.st/tunein/asxnature.pls",
L"Astra Trance",
L"https://orion.shoutca.st/tunein/astratrance.pls",
L"Atlas Corporation Trance",
L"https://orion.shoutca.st/tunein/asxatlas.pls",
L"Blues Channel",
L"https://orion.shoutca.st/tunein/asxblues.pls",
L"Christmas Channel",
L"https://orion.shoutca.st/tunein/asxchristmas.pls",
L"Classic Rock Hits",
L"https://orion.shoutca.st/tunein/asxrock.pls",
L"Classical Channel",
L"https://orion.shoutca.st/tunein/asxclassical.pls",
L"Country Music",
L"https://orion.shoutca.st/tunein/asxcountry.pls",
L"DKR TecHouse",
L"https://orion.shoutca.st/tunein/asxdkr.pls",
L"Dance '80s",
L"https://orion.shoutca.st/tunein/asx80s.pls",
L"Dance '90s",
L"https://orion.shoutca.st/tunein/asx90s.pls",
L"Ektoplazm PsyRadio",
L"https://orion.shoutca.st/tunein/asxektoplazm.pls",
L"Electro Swing & Funk",
L"https://orion.shoutca.st/tunein/asxpop.pls",
L"Emacore Trance",
L"https://orion.shoutca.st/tunein/asxemacore.pls",
L"Evergreen Hits",
L"https://orion.shoutca.st/tunein/asxoldies.pls",
L"French Skies Trance",
L"https://orion.shoutca.st/tunein/asxspies.pls",
L"Gate Of Paradise",
L"https://orion.shoutca.st/tunein/asxgate.pls",
L"Global Trance",
L"https://orion.shoutca.st/tunein/asxtrance.pls",
L"Heavy Metal",
L"https://orion.shoutca.st/tunein/asxmetal.pls",
L"House Channel",
L"https://orion.shoutca.st/tunein/asxcasw.pls",
L"Jazz Channel",
L"https://orion.shoutca.st/tunein/asxjyzz.pls",
//L"Kuno Trance",
//L"https://orion.shoutca.st/tunein/asxkuno.pls",
L"Larix W. Trance",
L"https://orion.shoutca.st/tunein/asxlarix.pls",
L"Liftburg Trance",
L"https://orion.shoutca.st/tunein/asxtomas.pls",
L"Matt Paul Uplifting",
L"https://orion.shoutca.st/tunein/asxmatt.pls",
L"Movie Themes",
L"https://orion.shoutca.st/tunein/asxmovie.pls",
L"New Wave '80s",
L"https://orion.shoutca.st/tunein/asxwave.pls",
L"Nick Turner Trance",
L"https://orion.shoutca.st/tunein/asxturner.pls",
L"Ori Uplift Trance",
L"https://orion.shoutca.st/tunein/asxori.pls",
L"Paradise Trance",
L"https://orion.shoutca.st/tunein/asxatg.pls",
L"PowerMixNetwork House",
L"https://orion.shoutca.st/tunein/pmnstream1.pls",
L"PowerMixNetwork UNDGND",
L"https://orion.shoutca.st/tunein/pmnstream2.pls",
L"PsychedelicTribe",
L"https://orion.shoutca.st/tunein/asxpsy.pls",
L"Pulsar Recordings",
L"https://orion.shoutca.st/tunein/asxpulsar.pls",
L"Reggae",
L"https://orion.shoutca.st/tunein/asxreggae.pls",
L"Rik Tights Trance",
L"https://orion.shoutca.st/tunein/asxtights.pls",
L"Sean & Xander Trance",
L"https://orion.shoutca.st/tunein/asxseanxander.pls",
L"Sonic Oblivion Trance",
L"https://orion.shoutca.st/tunein/asxoblivion.pls",
L"Sundance Recordings",
L"https://orion.shoutca.st/tunein/asxsundance.pls",
L"Techno Channel",
L"https://orion.shoutca.st/tunein/asxrik.pls",
L"The Space Trace",
L"https://orion.shoutca.st/tunein/asxalex.pls",
L"Victor Special Trance",
L"https://orion.shoutca.st/tunein/asxvictor.pls",
};