//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Winyl.rc
//
#define IDR_MAINFRAME                   100
#define IDR_ACCELERATOR                 101
#define IDD_DLGLIBRARY                  102
#define IDD_DLGSKIN                     103
#define IDD_DLGLANGUAGE                 104
#define IDD_DLGPROGRESS                 105
#define IDD_DLGPROPERTIES               106
#define IDD_DLGRENAME                   107
#define IDD_DLGABOUT                    108
#define IDD_DLGEQ                       110
#define IDD_DLGHOTKEYS                  111
#define IDD_DLGOPENURL                  112
#define IDD_DLGCONFIG                   113
#define IDD_DLGPAGEGENERAL              114
#define IDD_DLGPAGESYSTEM               115
#define IDD_DLGPAGEPOPUP                116
#define IDD_DLGPAGEMINI                 117
#define IDD_DLGSMART                    118
#define IDD_DLGSMARTTRACKS              119
#define IDD_DLGSMARTALBUMS              120
#define IDD_DLGPAGEGENERALXP            121
#define IDD_DLGNEWVERSION               123
#define IDD_DLGPAGETAGS                 124
#define IDD_DLGPAGELIBRARY              125
#define IDD_DLGPAGELIBRARYOPT           126
#define IDD_DLGPAGECOVER                127
#define IDD_DLGPAGELYRICS               128
#define IDI_ICON_WINYL                  200
#define IDI_ICON_SKIN                   201
#define IDI_ICON_HOTKEY                 202
#define IDI_ICON_FOLDER                 203
#define IDI_ICON_INFO                   204
#define IDI_ICON_PLUS                   205
#define IDI_ICON_TICK                   206
#define IDI_ICON_DRAG                   207
#define IDI_ICON_TRAY_PLAY              208
#define IDI_ICON_TRAY_PAUSE             209
#define IDI_ICON_TRAY_STOP              210
#define IDI_ICON_TRAY_NEXT              211
#define IDI_ICON_TRAY_PREV              212
#define IDI_ICON_TRAY_EXIT              213
#define IDI_ICON_THUMB_PLAY             214
#define IDI_ICON_THUMB_PAUSE            215
#define IDI_ICON_THUMB_STOP             216
#define IDI_ICON_THUMB_NEXT             217
#define IDI_ICON_THUMB_PREV             218
#define IDI_ICON_TAG_NEXT               219
#define IDI_ICON_TAG_PREV               220
#define IDI_ICON_LANG                   221
#define ID_MENU_LIBRARY                 701
#define ID_MENU_PLAY                    702
#define ID_MENU_PAUSE                   703
#define ID_MENU_STOP                    704
#define ID_MENU_NEXT                    705
#define ID_MENU_PREV                    706
#define ID_MENU_EXIT                    707
#define ID_MENU_SKIN                    708
#define ID_MENU_HIDETOTRAY              709
#define ID_MENU_SHUFFLE                 710
#define ID_MENU_REPEAT                  711
#define ID_MENU_LANGUAGE                712
#define ID_MENU_PROPERTIES              713
#define ID_MENU_PL_NEW                  714
#define ID_MENU_PL_RENAME               715
#define ID_MENU_PL_DELETE               716
#define ID_MENU_ABOUT                   717
#define ID_MENU_OPEN_FILE               718
#define ID_MENU_OPEN_FOLDER             719
#define ID_MENU_DELETE                  720
#define ID_MENU_DONATE                  721
#define ID_MENU_EQUALIZER               722
#define ID_MENU_LASTFM                  723
#define ID_MENU_LIST_PLAY               724
#define ID_MENU_SELECT_ALL              725
#define ID_MENU_HOTKEY                  726
#define ID_MENU_OPEN_URL                727
#define ID_MENU_OPEN_PLAYLIST           728
#define ID_MENU_POPUP_TL                729
#define ID_MENU_POPUP_TR                730
#define ID_MENU_POPUP_BL                731
#define ID_MENU_POPUP_BR                732
#define ID_MENU_POPUP_DISABLE           733
#define ID_MENU_POPUP                   734
#define ID_MENU_EFFECT                  735
#define ID_MENU_CONFIG                  736
#define ID_MENU_POPUP_CONFIG            737
#define ID_MENU_SEARCH_TRACK            738
#define ID_MENU_SEARCH_ALBUM            739
#define ID_MENU_SEARCH_ARTIST           740
#define ID_MENU_MINI                    741
#define ID_MENU_FILELOCATION            742
#define ID_MENU_SEARCH_ALL              743
#define ID_MENU_MUTE                    744
#define ID_MENU_SM_NEW                  745
#define ID_MENU_SM_DELETE               746
#define ID_MENU_SM_RENAME               747
#define ID_MENU_SM_EDIT                 748
#define ID_MENU_SM_UPDATE               749
#define ID_MENU_LIST_REPEAT             750
#define ID_MENU_SMOOTH                  751
#define ID_MENU_JUMPTO_ARTIST           752
#define ID_MENU_JUMPTO_ALBUM            753
#define ID_MENU_JUMPTO_YEAR             754
#define ID_MENU_JUMPTO_GENRE            755
#define ID_MENU_JUMPTO_FOLDER           756
#define ID_MENU_LYRICS_ALIGN_LEFT       757
#define ID_MENU_LYRICS_ALIGN_CENTER     758
#define ID_MENU_LYRICS_ALIGN_RIGHT      759
#define ID_MENU_LYRICS_FONT_DEFAULT     760
#define ID_MENU_LYRICS_FONT_SMALL       761
#define ID_MENU_LYRICS_FONT_MEDIUM      762
#define ID_MENU_LYRICS_FONT_LARGE       763
#define ID_MENU_LYRICS_FONT_LARGEST     764
#define ID_MENU_LYRICS_FONT_BOLD        765
#define ID_MENU_LYRICS_SOURCE           766
#define ID_MENU_LYRICS_COPY             767
#define ID_MENU_LYRICS_SAVE             768
#define ID_MENU_LYRICS_GOOGLE           769
#define ID_MENU_LYRICS_PROV_OFF         770
#define ID_MENU_LYRICS_PROV_AUTO        771
#define ID_MENU_LYRICS_PROV_1           772
#define ID_MENU_LYRICS_PROV_2           773
#define ID_MENU_LYRICS_PROV_3           774
#define ID_MENU_LYRICS_PROV_4           775
#define ID_MENU_LYRICS_PROV_5           776
#define ID_MENU_LYRICS_PROV_6           777
#define ID_MENU_LYRICS_PROV_7           778
#define ID_MENU_LYRICS_PROV_8           779
#define ID_MENU_LYRICS_PROV_9           780
#define ID_MENU_LYRICS_PROV_10          781
#define IDC_LIST_SKIN                   1003
#define IDC_STATIC_PREVIEW              1004
#define IDC_TEXT_AUTHOR                 1005
#define IDC_TEXT_VERSION                1006
#define IDC_TEXT_INFO                   1007
#define IDC_STATIC_SELECTSKIN           1008
#define IDC_STATIC_PREVIEW2             1009
#define IDC_STATIC_INFO                 1010
#define IDC_STATIC_AUTHOR               1011
#define IDC_STATIC_VERSION              1012
#define IDC_LIST_LANGUAGE               1013
#define IDC_STATIC_DESC                 1014
#define IDC_STATIC_SELECT               1015
#define IDC_PROGRESS                    1016
#define IDC_STATIC_FILE                 1017
#define IDC_EDIT_RENAME                 1033
#define IDC_STATIC_RENAME               1034
#define IDC_STATIC_SITE                 1035
#define IDC_STATIC_MAIL                 1036
#define IDC_SLIDER_GAIN                 1043
#define IDC_SLIDER_EQ0                  1044
#define IDC_SLIDER_EQ1                  1045
#define IDC_SLIDER_EQ2                  1046
#define IDC_SLIDER_EQ3                  1047
#define IDC_SLIDER_EQ4                  1048
#define IDC_SLIDER_EQ5                  1049
#define IDC_SLIDER_EQ6                  1050
#define IDC_SLIDER_EQ7                  1051
#define IDC_SLIDER_EQ8                  1052
#define IDC_SLIDER_EQ9                  1053
#define IDC_BUTTON_ASIO_CONFIG          1054
#define IDC_BUTTON_POPUP_TEST           1055
#define IDC_BUTTON_SAVE                 1056
#define IDC_CHECK_EQ                    1058
#define IDC_CHECK_PLAY_COUNT            1060
#define IDC_CHECK_PROXY                 1061
#define IDC_CHECK_SELECT_ALL            1062
#define IDC_CHECK_TRACKS_COUNT          1063
#define IDC_COMBO_FROM                  1064
#define IDC_COMBO_PLAY_COUNT            1065
#define IDC_COMBO_POPUP_HIDE            1066
#define IDC_COMBO_TRACKS_COUNT          1067
#define IDC_SLIDER_OPACITY              1068
#define IDC_STATIC_P12                  1069
#define IDC_STATIC_ZERO                 1070
#define IDC_STATIC_M12                  1071
#define IDC_STATIC_EQ0                  1072
#define IDC_STATIC_EQ1                  1073
#define IDC_STATIC_EQ2                  1074
#define IDC_STATIC_EQ3                  1075
#define IDC_STATIC_EQ4                  1076
#define IDC_STATIC_EQ5                  1077
#define IDC_STATIC_EQ6                  1078
#define IDC_STATIC_EQ7                  1079
#define IDC_STATIC_EQ8                  1080
#define IDC_STATIC_EQ9                  1081
#define IDC_STATIC_PREAMP               1082
#define IDC_STATIC_PRESET               1083
#define IDC_LIST_KEYS                   1084
#define IDC_EDIT_NAME                   1085
#define IDC_EDIT_URL                    1086
#define IDC_STATIC_NAME                 1087
#define IDC_STATIC_URL                  1088
#define IDC_STATIC_TRANSLATED           1089
#define IDC_TAB_CONFIG                  1090
#define IDC_EDIT_PROXY_HOST             1091
#define IDC_EDIT_PROXY_PORT             1092
#define IDC_STATIC_POPUP_TIME           1093
#define IDC_STATIC_POPUP_DELAY          1094
#define IDC_STATIC_POPUP_POSITION       1095
#define IDC_STATIC_POPUP_EFFECT         1096
#define IDC_COMBO_POPUP_POSITION        1097
#define IDC_COMBO_POPUP_SHOW            1098
#define IDC_STATIC_POPUP_SEC1           1099
#define IDC_SLIDER_POPUP_HOLD           1100
#define IDC_STATIC_POPUP_VIEW           1101
#define IDC_SLIDER_POPUP_HIDE           1102
#define IDC_STATIC_POPUP_SEC2           1103
#define IDC_STATIC_POPUP_SEC3           1104
#define IDC_SLIDER_POPUP_SHOW           1105
#define IDC_STATIC_POPUP_START          1106
#define IDC_STATIC_POPUP_END            1107
#define IDC_COMBO_DEVICE                1108
#define IDC_EDIT_PROXY_LOGIN            1109
#define IDC_EDIT_PROXY_PASS             1110
#define IDC_CHECK_PROXY_AUTH            1111
#define IDC_STATIC_PROXY_HOST           1112
#define IDC_STATIC_PROXY_PORT           1113
#define IDC_STATIC_PROXY_LOGIN          1114
#define IDC_STATIC_PROXY_PASS           1115
#define IDC_STATIC_PROXY                1116
#define IDC_STATIC_DEVICE               1117
#define IDC_CHECK_LASTFM                1118
#define IDC_STATIC_POPUP_EFFECT_HIDE    1119
#define IDC_STATIC_OPACITY              1120
#define IDC_CHECK_BIT32                 1121
#define IDC_CHECK_SOFTMIX               1122
#define IDC_STATIC_RECT                 1123
#define IDC_STATIC_FROM                 1124
#define IDC_EDIT_FROM                   1125
#define IDC_CHECK_RATING                1126
#define IDC_CHECK_LAST_PLAYED           1127
#define IDC_CHECK_LAST_ADDED            1128
#define IDC_COMBO_RATING                1129
#define IDC_COMBO_LAST_PLAYED           1130
#define IDC_COMBO_LAST_ADDED            1131
#define IDC_EDIT_TIMES                  1132
#define IDC_COMBO_RATING_STAR           1133
#define IDC_COMBO_LAST_ADDED_DATE       1134
#define IDC_COMBO_LAST_PLAYED_DATE      1135
#define IDC_STATIC_TIMES                1136
#define IDC_STATIC_TOOLTIP              1137
#define IDC_COMBO_TYPE                  1138
#define IDC_COMBO_FILTER                1139
#define IDC_STATIC_PLUS                 1140
#define IDC_EDIT_COUNT                  1141
#define IDC_CHECK_RANDOM                1142
#define IDC_CHECK_UPDATE                1143
#define IDC_STATIC_ICON_WINYL           1144
#define IDC_EDIT_TRACKS_COUNT           1145
#define IDC_STATIC_TRACKS_COUNT         1146
#define IDC_CHECK_ASSOC                 1147
#define IDC_BUTTON_ASSOC                1148
#define IDC_LIST_ASSOC                  1149
#define IDC_CHECK_ARTISTS               1150
#define IDC_CHECK_ALBUMS                1151
#define IDC_CHECK_GENRES                1152
#define IDC_CHECK_YEARS                 1153
#define IDC_CHECK_FOLDERS               1154
#define IDC_CHECK_RADIOS                1155
#define IDC_CHECK_SMARTLISTS            1156
#define IDC_CHECK_PLAYLISTS             1157
#define IDC_CHECK_MSN                   1158
#define IDC_STATIC_LIBRARY_VIEW         1159
#define IDC_STATIC_SERVICES             1160
#define IDC_STATIC_ASSOCIATIONS         1161
#define IDC_STATIC_OPTIONS              1162
#define IDC_STATIC_COUNT                1163
#define IDC_CHECK_ADD_ALL               1164
#define IDC_CHECK_PLAY_FOCUS            1165
#define IDC_STATIC_BEHAVIOR             1166
#define IDC_PROGRESS_TAGS               1168
#define IDC_RADIO_ALWAYS_ON_TOP         1176
#define IDC_RADIO_ALWAYS_ON_DESKTOP     1177
#define IDC_RADIO_ALWAYS_ON_OFF         1178
#define IDC_RADIO_DIRECTSOUND           1179
#define IDC_RADIO_WASAPI                1180
#define IDC_RADIO_ASIO                  1181
#define IDC_CHECK_UPDATES_AUTO          1183
#define IDC_COMBO_ALL_ANY               1185
#define IDC_STATIC_FOLLOWING_RULES      1186
#define IDC_BUTTON_MINIMIZE             1187
#define IDC_PROGRESS_NEWVER             1188
#define IDC_TAB_PROPERTIES              1189
#define IDC_STATIC_TITLE                1190
#define IDC_STATIC_ARTIST               1191
#define IDC_STATIC_ALBUM                1192
#define IDC_STATIC_ALBUMARTIST          1193
#define IDC_STATIC_COMPOSER             1194
#define IDC_STATIC_YEAR                 1195
#define IDC_STATIC_TRACK                1196
#define IDC_STATIC_TRACKTOTAL           1197
#define IDC_STATIC_DISC                 1198
#define IDC_STATIC_DISCTOTAL            1199
#define IDC_STATIC_GENRE                1200
#define IDC_STATIC_COMMENT              1201
#define IDC_CHECK_TITLE                 1202
#define IDC_CHECK_ARTIST                1203
#define IDC_CHECK_ALBUM                 1204
#define IDC_CHECK_ALBUMARTIST           1205
#define IDC_CHECK_COMPOSER              1206
#define IDC_CHECK_YEAR                  1207
#define IDC_CHECK_TRACK                 1208
#define IDC_CHECK_TRACKTOTAL            1209
#define IDC_CHECK_DISC                  1210
#define IDC_CHECK_DISCTOTAL             1211
#define IDC_CHECK_GENRE                 1212
#define IDC_CHECK_COMMENT               1213
#define IDC_EDIT_TITLE                  1214
#define IDC_EDIT_ARTIST                 1215
#define IDC_EDIT_ALBUM                  1216
#define IDC_EDIT_ALBUMARTIST            1217
#define IDC_EDIT_COMPOSER               1218
#define IDC_EDIT_YEAR                   1219
#define IDC_EDIT_TRACK                  1220
#define IDC_EDIT_TRACKTOTAL             1221
#define IDC_EDIT_DISC                   1222
#define IDC_EDIT_DISCTOTAL              1223
#define IDC_EDIT_GENRE                  1224
#define IDC_EDIT_COMMENT                1225
#define IDC_STATIC_FILE2                1226
#define IDC_STATIC_QUALITY              1227
#define IDC_EDIT_FILE                   1228
#define IDC_EDIT_QUALITY                1229
#define IDC_STATIC_NEWVERSION           1230
#define IDC_TAB_LIBRARY                 1231
#define IDC_STATIC_LINE1                1232
#define IDC_STATIC_LINE2                1233
#define IDC_LIST_FOLDERS                1234
#define IDC_BUTTON_ADD                  1235
#define IDC_BUTTON_DELETE               1236
#define IDC_STATIC_BASIC                1237
#define IDC_STATIC_ADVANCED             1238
#define IDC_CHECK_REMOVE_MISSING        1239
#define IDC_CHECK_IGNORE_DELETED        1240
#define IDC_CHECK_FIND_MOVED            1241
#define IDC_CHECK_RESCAN_ALL            1242
#define IDC_CHECK_COMPOSERS             1243
#define IDC_STATIC_COVER                1244
#define IDC_STATIC_COVER2               1245
#define IDC_BUTTON_COVER_LOAD           1246
#define IDC_BUTTON_COVER_REMOVE         1247
#define IDC_STATIC_NOCOVER              1248
#define IDC_STATIC_DRAGCOVER            1249
#define IDC_CHECK_SAVE_COVER_TAGS       1250
#define IDC_CHECK_SAVE_COVER_FILE       1251
#define IDC_STATIC_LYRICIST             1252
#define IDC_CHECK_LYRICIST              1253
#define IDC_EDIT_LYRICIST               1254
#define IDC_EDIT_LYRICS                 1255
#define IDC_CHECK_SAVE_LYRICS_TAGS      1256
#define IDC_CHECK_SAVE_LYRICS_FILE      1257
#define IDC_STATIC_NEXT_PREV            1258
#define IDC_STATIC_ZORDER               1259
#define IDC_BUTTON_COVER_GOOGLE         1260
#define ID_KEY_DELETE                   32771
#define ID_KEY_SPACE                    32772
#define ID_KEY_ENTER                    32773
#define ID_KEY_CTRL_LEFT                32774
#define ID_KEY_CTRL_RIGHT               32775
#define ID_KEY_CTRL_SPACE               32776
#define ID_KEY_F3                       32777
#define ID_KEY_F4                       32778
#define ID_KEY_F5                       32779
#define ID_KEY_F6                       32780
#define ID_KEY_F7                       32781
#define ID_KEY_F8                       32782
#define ID_KEY_MUTE                     32783
#define ID_KEY_REPEAT                   32784
#define ID_KEY_SHUFFLE                  32785
#define ID_KEY_PL_FILE                  32786
#define ID_KEY_PL_FOLDER                32787
#define ID_KEY_PL_URL                   32788
#define ID_KEY_SELECT_ALL               32789
#define ID_KEY_CTRL_C                   32790
#define ID_KEY_CTRL_INS                 32791
#define ID_KEY_CTRL_F                   32792
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1261
#define _APS_NEXT_SYMED_VALUE           129
#endif
#endif
